### ISSUE TITLE
test fails with missing 0041b.svg

### ISSUE THREAD

**Issue by 2600box** [cayennes/kanji-colorize#52]
not sure what is going on. the test fails and i can't figure out how to fix it...

```
python -m kanjicolorizer.colorizer
**********************************************************************
File "/Users/nippon/dev/kanji-colorize/kanjicolorizer/colorizer.py", line 102, in __main__.KanjiVG.__init__
Failed example:
    k = KanjiVG('Л')
Expected:
    Traceback (most recent call last):
        ...
    kanjicolorizer.colorizer.InvalidCharacterError: ('\u041b', '')
Got:
    Traceback (most recent call last):
      File "/Users/nippon/dev/kanji-colorize/kanjicolorizer/colorizer.py", line 114, in __init__
        'r', encoding='utf-8') as f:
    FileNotFoundError: [Errno 2] No such file or directory: '/Users/nippon/dev/kanji-colorize/kanjicolorizer/data/kanjivg/kanji/0041b.svg'
    <BLANKLINE>
    The above exception was the direct cause of the following exception:
    <BLANKLINE>
    Traceback (most recent call last):
      File "/Users/nippon/.pyenv/versions/3.7.3/lib/python3.7/doctest.py", line 1329, in __run
        compileflags, 1), test.globs)
      File "<doctest __main__.KanjiVG.__init__[6]>", line 1, in <module>
        k = KanjiVG('Л')
      File "/Users/nippon/dev/kanji-colorize/kanjicolorizer/colorizer.py", line 118, in __init__
        raise InvalidCharacterError(character, variant) from e
    InvalidCharacterError: ('Л', '')
**********************************************************************
1 items had failures:
   1 of   7 in __main__.KanjiVG.__init__
***Test Failed*** 1 failures.
```

**Comment by jblumie** [comment]
Fixed with #79, although I don't know if it is a proper fix as I note on the commit description, but I think so.

It's just expecting to get the full qualified name `kanjicolorizer.colorizer.InvalidCharacterError` but got `InvalidCharacterError` instead
